services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      API_URL: http://backend:8080

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - backend


  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=/
      - BACKEND_URL=rpc://
      - BROKER_URL=amqp://admin:admin@localhost:5672/
      - REDIS_BACKEND_URL=redis://redis:6379/0
      - DB_USER=root
      - DB_PASSWORD=Zm.1575098153
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=fast
      - DB_CHARSET=utf8
      - DB_AUTH_PLUGIN=mysql_native_password
      - CELERY_BROKER_URL=amqp://admin:admin@rabbitmq:5672/
      - CELERY_RESULT_BACKEND=rpc://
      - CELERY_LOG_LEVEL=debug
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_HOST=redis
      - FLOWER_BASIC_AUTH=admin:password
      - MONGODB_URL=mongodb://mongodb:27017
    depends_on:
      - mysql
      - mongodb
      - flower
      - elasticsearch

  celery:
    build: ./backend
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=/
      - BACKEND_URL=rpc://
      - BROKER_URL=amqp://admin:admin@localhost:5672/
      - REDIS_BACKEND_URL=redis://redis:6379/0
      - DB_USER=root
      - DB_PASSWORD=Zm.1575098153
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=fast
      - DB_CHARSET=utf8
      - DB_AUTH_PLUGIN=mysql_native_password
      - CELERY_BROKER_URL=amqp://admin:admin@rabbitmq:5672/
      - CELERY_RESULT_BACKEND=rpc://
      - CELERY_LOG_LEVEL=debug
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_HOST=redis
      - FLOWER_BASIC_AUTH=admin:password
      - MONGODB_URL=mongodb://mongodb:27017
    depends_on:
      - rabbitmq
    command: celery -A app.celery_task.tasks worker --loglevel=info

  flower:
    build: ./backend
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=/
      - BACKEND_URL=rpc://
      - BROKER_URL=amqp://admin:admin@localhost:5672/
      - REDIS_BACKEND_URL=redis://redis:6379/0
      - DB_USER=root
      - DB_PASSWORD=Zm.1575098153
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=fast
      - DB_CHARSET=utf8
      - DB_AUTH_PLUGIN=mysql_native_password
      - CELERY_BROKER_URL=amqp://admin:admin@rabbitmq:5672/
      - CELERY_RESULT_BACKEND=rpc://
      - CELERY_LOG_LEVEL=debug
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_HOST=redis
      - FLOWER_BASIC_AUTH=admin:password
      - MONGODB_URL=mongodb://mongodb:27017
    ports:
      - "5555:5555"
    depends_on:
      - celery
    command: flower --app=app.celery_task.tasks --broker=amqp://admin:admin@rabbitmq:5672// --port=5555

  mysql:
    build: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Zm.1575098153

  mongodb:
    build: ./mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data/db

  elasticsearch:
    build: ./elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  rabbitmq:
    build: ./rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"


  redis:
    build: ./redis
    ports:
      - "6379:6379"

  spacy:
    build: ./spacy

  master:
    image: crawlabteam/crawlab:latest
    container_name: crawlab_example_master
    environment:
      CRAWLAB_NODE_MASTER: "Y"
      CRAWLAB_MONGO_HOST: "mongo"
    volumes:
      - "./.crawlab/master:/root/.crawlab"
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  worker01:
    image: crawlabteam/crawlab:latest
    container_name: crawlab_example_worker01
    environment:
      CRAWLAB_NODE_MASTER: "N"
      CRAWLAB_GRPC_ADDRESS: "master"
      CRAWLAB_FS_FILER_URL: "http://master:8080/api/filer"
    volumes:
      - "./.crawlab/worker01:/root/.crawlab"
    depends_on:
      - master

  worker02:
    image: crawlabteam/crawlab:latest
    container_name: crawlab_example_worker02
    environment:
      CRAWLAB_NODE_MASTER: "N"
      CRAWLAB_GRPC_ADDRESS: "master"
      CRAWLAB_FS_FILER_URL: "http://master:8080/api/filer"
    volumes:
      - "./.crawlab/worker02:/root/.crawlab"
    depends_on:
      - master

  mongo:
    image: mongo:4.2
    container_name: crawlab_example_mongo
    restart: always