# 登录
POST http://localhost:8000/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin",
  "grant_type": "",
  "client_id": "",
  "client_secret": ""
}

###

# 获取受保护的数据
GET http://localhost:8000/protected
Authorization: Bearer {eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNTc1MDk4MTUzQHFxLmNvbSIsImV4cCI6MTY3NzIzODcxN30.xbHR_RJCQxxLnzlYCy0KaHvlp4SrXP8LK3EADnd_924}