global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8080']
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:80']
  - job_name: 'celery'
    static_configs:
      - targets: ['celery:5555']
