USE mysql;
CREATE DATABASE IF NOT EXISTS fast;
ALTER USER 'root' IDENTIFIED WITH mysql_native_password BY 'Zm.1575098153';
USE fast;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL
);